// <auto-generated />
using Ecommerce.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ecommerce.Repository.Migrations
{
    [DbContext(typeof(EcommerceContext))]
    [Migration("20210815230414_InicioRep")]
    partial class InicioRep
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("Ecommerce.Domain.Models.Fruta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<string>("Foto")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Frutas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Banana Prata",
                            Estoque = 35,
                            Foto = "banana.png",
                            Nome = "Banana",
                            Quantidade = 15,
                            Valor = 4.99m
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Mamão Papaia",
                            Estoque = 40,
                            Foto = "mamao.png",
                            Nome = "Mamão",
                            Quantidade = 21,
                            Valor = 5.75m
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Maça Fuji",
                            Estoque = 51,
                            Foto = "maça.png",
                            Nome = "Maça",
                            Quantidade = 35,
                            Valor = 3.25m
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Laranja Bahia",
                            Estoque = 57,
                            Foto = "laranja.png",
                            Nome = "Laranja",
                            Quantidade = 42,
                            Valor = 6.46m
                        });
                });

            modelBuilder.Entity("Ecommerce.Domain.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("NomeCompleto")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
